// <auto-generated />
using System;
using Alza.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alza.Persistence.Migrations
{
    [DbContext(typeof(AlzaDbContext))]
    [Migration("20241203134056_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Alza.Persistence.Models.Product", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Product_CreatedAt");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("CreatedAt"), false);

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Product_Name");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Name"), false);

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aeae8fb4-bc85-4046-a7f0-3e4452f8737c"),
                            CreatedAt = new DateTime(2024, 11, 30, 13, 40, 56, 672, DateTimeKind.Utc).AddTicks(7994),
                            Description = "High-end gaming laptop with RTX 4090.",
                            ImageUrl = "https://example.com/laptop.png",
                            Name = "Gaming Laptop",
                            Price = 1499.99m
                        },
                        new
                        {
                            Id = new Guid("dd7ee6a1-403e-4d14-9f7b-7efc77b0cb7f"),
                            CreatedAt = new DateTime(2024, 11, 30, 13, 40, 56, 672, DateTimeKind.Utc).AddTicks(7994),
                            Description = "Ergonomic wireless mouse with adjustable DPI.",
                            ImageUrl = "https://example.com/mouse.png",
                            Name = "Wireless Mouse",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = new Guid("b1818275-0beb-4911-9aeb-2f09b7923525"),
                            CreatedAt = new DateTime(2024, 11, 30, 13, 40, 56, 672, DateTimeKind.Utc).AddTicks(7994),
                            Description = "RGB mechanical keyboard with Cherry MX switches.",
                            ImageUrl = "https://example.com/keyboard.png",
                            Name = "Mechanical Keyboard",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = new Guid("571f36a2-4a0f-400d-9595-7ebcf66d0a86"),
                            CreatedAt = new DateTime(2024, 12, 1, 13, 40, 56, 672, DateTimeKind.Utc).AddTicks(7994),
                            Description = "34-inch ultrawide QHD monitor.",
                            ImageUrl = "https://example.com/monitor.png",
                            Name = "Ultrawide Monitor",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = new Guid("9751d27e-0ec9-46fc-ab25-2cbdac46a45b"),
                            CreatedAt = new DateTime(2024, 12, 1, 13, 40, 56, 672, DateTimeKind.Utc).AddTicks(7994),
                            Description = "Ergonomic gaming chair with lumbar support.",
                            ImageUrl = "https://example.com/chair.png",
                            Name = "Gaming Chair",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = new Guid("9f88a461-1678-4773-a059-0c517e311c68"),
                            CreatedAt = new DateTime(2024, 12, 1, 13, 40, 56, 672, DateTimeKind.Utc).AddTicks(7994),
                            Description = "LED desk lamp with adjustable brightness.",
                            ImageUrl = "https://example.com/lamp.png",
                            Name = "Desk Lamp",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = new Guid("35f26883-9b3f-4c59-9bbd-4d09848a5fbc"),
                            CreatedAt = new DateTime(2024, 12, 2, 13, 40, 56, 672, DateTimeKind.Utc).AddTicks(7994),
                            Description = "1TB external SSD for high-speed storage.",
                            ImageUrl = "https://example.com/ssd.png",
                            Name = "External SSD",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = new Guid("2f829254-630c-46bb-b1e6-886072f8e7e8"),
                            CreatedAt = new DateTime(2024, 12, 2, 13, 40, 56, 672, DateTimeKind.Utc).AddTicks(7994),
                            Description = "Over-ear noise cancelling headphones.",
                            ImageUrl = "https://example.com/headphones.png",
                            Name = "Noise Cancelling Headphones",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = new Guid("c254dd20-882c-488e-b2f1-1ebb06ec9b68"),
                            CreatedAt = new DateTime(2024, 12, 2, 13, 40, 56, 672, DateTimeKind.Utc).AddTicks(7994),
                            Description = "Latest flagship smartphone.",
                            ImageUrl = "https://example.com/phone.png",
                            Name = "Smartphone",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = new Guid("e9a62381-af0f-495c-9534-aa2ae008a4b4"),
                            CreatedAt = new DateTime(2024, 12, 3, 13, 40, 56, 672, DateTimeKind.Utc).AddTicks(7994),
                            Description = "Lightweight tablet with pen support.",
                            ImageUrl = "https://example.com/tablet.png",
                            Name = "Tablet",
                            Price = 799.99m
                        },
                        new
                        {
                            Id = new Guid("89770280-7299-4066-8b19-c999d1b02ebb"),
                            CreatedAt = new DateTime(2024, 12, 3, 13, 40, 56, 672, DateTimeKind.Utc).AddTicks(7994),
                            Description = "Bluetooth portable speaker with 10-hour battery life.",
                            ImageUrl = "https://example.com/speaker.png",
                            Name = "Portable Speaker",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = new Guid("7b248367-556e-4fc2-baa3-2d4c69da7281"),
                            CreatedAt = new DateTime(2024, 12, 3, 13, 40, 56, 672, DateTimeKind.Utc).AddTicks(7994),
                            Description = "1080p HD webcam for streaming.",
                            ImageUrl = "https://example.com/webcam.png",
                            Name = "Webcam",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = new Guid("f80fad30-ea08-4d96-8357-d9c81bbe1d0f"),
                            CreatedAt = new DateTime(2024, 11, 30, 13, 40, 56, 672, DateTimeKind.Utc).AddTicks(7994),
                            Description = "20,000mAh portable power bank.",
                            ImageUrl = "https://example.com/powerbank.png",
                            Name = "Power Bank",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = new Guid("77e00846-e138-499f-952a-35cfd206c88d"),
                            CreatedAt = new DateTime(2024, 12, 1, 13, 40, 56, 672, DateTimeKind.Utc).AddTicks(7994),
                            Description = "USB-C docking station with multiple ports.",
                            ImageUrl = "https://example.com/dock.png",
                            Name = "Docking Station",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = new Guid("d48f9cd5-0db7-47e7-beae-5c3741ead07e"),
                            CreatedAt = new DateTime(2024, 12, 2, 13, 40, 56, 672, DateTimeKind.Utc).AddTicks(7994),
                            Description = "True wireless earbuds with active noise cancellation.",
                            ImageUrl = "https://example.com/earbuds.png",
                            Name = "Wireless Earbuds",
                            Price = 149.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
